// <auto-generated />
namespace WebApp_MVC_L59_CRUD_RZR_BS_Code_31523.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class altercolumnchangetypeofcountry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altercolumnchangetypeofcountry));
        
        string IMigrationMetadata.Id
        {
            get { return "202305311513423_altercolumnchangetypeofcountry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
