// <auto-generated />
namespace WebApp_MVC_L61_LoginHomepage_60123.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class altermodelproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altermodelproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202305312154287_altermodelproperty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
