// <auto-generated />
namespace WebApp_MVC_Code_L62_ChngePas_6123.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class createdatabaseandtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createdatabaseandtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202306011052295_createdatabaseandtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
