//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC_L63_DB_Apprch_Mstr_2623.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobSeeker
    {
        public int JobSeeker_id { get; set; }
        public string JobSeeker_name { get; set; }
        public string JobSeeker_email { get; set; }
        public string JobSeeker_password { get; set; }
        public Nullable<int> JobSeeker_status { get; set; }
    }
}
