//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_MVC_L63_DB_Apprch_Mstr_2623.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserType
    {
        public int UserType_id { get; set; }
        public string UserType_name { get; set; }
    }
}
