// <auto-generated />
namespace WebApp_MVC_L56_CodeFirst_30523.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class altertableaddsalarycolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(altertableaddsalarycolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "202305301301577_altertableaddsalarycolumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
